INSERT INTO miobservador.provincia (nombreProvincia) VALUES
('Buenos Aires-GBA'),
('Capital Federal'),
('Catamarca'),
('Chaco'),
('Chubut'),
('Córdociudadba'),
('Corrientes'),
('Entre Ríos'),
('Formosa'),
('Jujuy'),
('La Pampa'),
('La Rioja'),
('Mendoza'),
('Misiones'),
('Neuquén'),
('Río Negro'),
('Salta'),
('San Juan'),
('San Luis'),
('Santa Cruz'),
('Santa Fe'),
('Santiago del Estero'),
('Tierra del Fuego'),
('Tucumán');


INSERT INTO miobservador.ciudad (nombreCiudad, idProvincia) VALUES
('Achiras',81),
('Adelia Maria',81),
('Agua de Oro',81),
('Alcira Gigena',81),
('Aldea Santa Maria',81),
('Alejandro Roca',81),
('Alejo Ledesma',81),
('Alicia',81),
('Almafuerte',81),
('Alpa Corral',81),
('Alta Gracia',81),
('Alto Alegre',81),
('Alto de Los Quebrachos',81),
('Altos de Chipion',81),
('Amboy',81),
('Ambul',81),
('Ana Zumaran',81),
('Anisacate',81),
('Arguello',81),
('Arias',81),
('Arroyito',81),
('Arroyo Algodon',81),
('Arroyo Cabral',81),
('Arroyo Los Patos',81),
('Assunta',81),
('Atahona',81),
('Ausonia',81),
('Avellaneda',81),
('Ballesteros',81),
('Ballesteros Sud',81),
('Balnearia',81),
('Bañado de Soto',81),
('Bell Ville',81),
('Bengolea',81),
('Benjamin Gould',81),
('Berrotaran',81),
('Bialet Masse',81),
('Bouwer',81),
('Brinkmann',81),
('Buchardo',81),
('Bulnes',81),
('Cabalango',81),
('Calamuchita',81),
('Calchin',81),
('Calchin Oeste',81),
('Calmayo',81),
('Camilo Aldao',81),
('Caminiaga',81),
('Cañada de Luque',81),
('Cañada de Machado',81),
('Cañada de Rio Pinto',81),
('Cañada del Sauce',81),
('Canals',81),
('Candelaria Sud',81),
('Capilla de Remedios',81),
('Capilla de Siton',81),
('Capilla del Carmen',81),
('Capilla del Monte',81),
('Córdoba',81),
('Capitan Gral B. O´Higgins',81),
('Carnerillo',81),
('Carrilobo',81),
('Casa Grande',81),
('Cavanagh',81),
('Cerro Colorado',81),
('Chaján',81),
('Chalacea',81),
('Chañar Viejo',81),
('Chancaní',81),
('Charbonier',81),
('Charras',81),
('Chazón',81),
('Chilibroste',81),
('Chucul',81),
('Chuña',81),
('Chuña Huasi',81),
('Churqui Cañada',81),
('Cienaga Del Coro',81),
('Cintra',81),
('Col. Almada',81),
('Col. Anita',81),
('Col. Barge',81),
('Col. Bismark',81),
('Col. Bremen',81),
('Col. Caroya',81),
('Col. Italiana',81),
('Col. Iturraspe',81),
('Col. Las Cuatro Esquinas',81),
('Col. Las Pichanas',81),
('Col. Marina',81),
('Col. Prosperidad',81),
('Col. San Bartolome',81),
('Col. San Pedro',81),
('Col. Tirolesa',81),
('Col. Vicente Aguero',81),
('Col. Videla',81),
('Col. Vignaud',81),
('Col. Waltelina',81),
('Colazo',81),
('Comechingones',81),
('Conlara',81),
('Copacabana',81),
('Coronel Baigorria',81),
('Coronel Moldes',81),
('Corral de Bustos',81),
('Corralito',81),
('Cosquín',81),
('Costa Sacate',81),
('Cruz Alta',81),
('Cruz de Caña',81),
('Cruz del Eje',81),
('Cuesta Blanca',81),
('Dean Funes',81),
('Del Campillo',81),
('Despeñaderos',81),
('Devoto',81),
('Diego de Rojas',81),
('Dique Chico',81),
('El Arañado',81),
('El Brete',81),
('El Chacho',81),
('El Crispín',81),
('El Fortín',81),
('El Manzano',81),
('El Rastreador',81),
('El Rodeo',81),
('El Tío',81),
('Elena',81),
('Embalse',81),
('Esquina',81),
('Estación Gral. Paz',81),
('Estación Juárez Celman',81),
('Estancia de Guadalupe',81),
('Estancia Vieja',81),
('Etruria',81),
('Eufrasio Loza',81),
('Falda del Carmen',81),
('Freyre',81),
('Gral. Baldissera',81),
('Gral. Cabrera',81),
('Gral. Deheza',81),
('Gral. Fotheringham',81),
('Gral. Levalle',81),
('Gral. Roca',81),
('Guanaco Muerto',81);
